In [1]:
import torch
import sys
import numpy as np
from utils import *
from model import *
%matplotlib inline
%load_ext autoreload


In [3]:
import numpy as np
from skimage.io import imsave, imread
import imagecodecs

path_august = 'glaciers_mapping_downsampled/test/'

image_juillet = imagecodecs.imread(path_august + 'date0/patch_0_0.tif')
image_aout = imagecodecs.imread(path_august + 'date1/patch_0_0.tif')


In [7]:
import numpy as np

def normalize_image_patch(patch):
    """
    Normalize image patch with 4 bands
    
    Parameters
    ----------
    patch : numpy array
        Image patch numpy array with shape (height, width, num_bands)
    
    Returns
    -------
    normalized_patch : numpy array
        Normalized image patch numpy array with the same shape as the input patch
    """
    normalized_patch = np.zeros_like(patch, dtype=np.float32)
    
    for band in range(patch.shape[2]):
        band_data = patch[:, :, band]
        min_val = np.min(band_data)
        max_val = np.max(band_data)
        
        # Normalize each band to values between 0 and 1
        normalized_band = (band_data - min_val) / (max_val - min_val + 1e-8)
        normalized_patch[:, :, band] = normalized_band
    
    return normalized_patch


In [8]:
norm_image= normalize_image_patch(image_juillet)
print(norm_image)

[[[2.01396141e-02 1.79999992e-02 1.21759633e-02 4.20841686e-02]
  [2.30281632e-02 1.69166662e-02 1.17831901e-02 4.55911867e-02]
  [2.34293509e-02 2.16666665e-02 9.13197175e-03 4.78456914e-02]
  ...
  [5.39998412e-02 4.75833341e-02 8.64100549e-03 0.00000000e+00]
  [5.68081513e-02 4.69999984e-02 8.05184618e-03 0.00000000e+00]
  [5.59255444e-02 4.68333326e-02 7.85546005e-03 0.00000000e+00]]

 [[1.82941519e-02 1.51666664e-02 1.21759633e-02 3.04358713e-02]
  [1.68498755e-02 1.84999984e-02 1.15868039e-02 2.90581156e-02]
  [1.44427503e-02 1.33333337e-02 1.23723494e-02 5.28557114e-02]
  ...
  [5.72895780e-02 4.78333309e-02 8.44461937e-03 0.00000000e+00]
  [5.52034043e-02 4.66666669e-02 9.42655187e-03 0.00000000e+00]
  [5.48824556e-02 4.64166664e-02 8.54281243e-03 0.00000000e+00]]

 [[2.69598011e-02 3.28333303e-02 3.83935608e-02 8.01603273e-02]
  [3.54649760e-02 3.12500000e-02 1.19599372e-01 7.64028057e-02]
  [2.80028880e-02 2.08333321e-02 3.13236453e-02 6.26252517e-02]
  ...
  [5.43207899e-02 